import { getServerLocale } from '@/lib/i18n/server';

export const metadata = { title: 'Terms of Service · MyHim Studio' };

export default async function Page() {
  const locale = await getServerLocale();
  return (
    <>
      <h1 className="text-3xl font-bold">{locale === 'en' ? 'Terms of Service' : '服务条款'}</h1>
      <p className="text-sm text-fg-subtle">
        {locale === 'en' ? 'Last updated' : '最后更新'}: {new Date().toISOString().slice(0, 10)}
      </p>
      {locale === 'en' ? <EN /> : <ZH />}
    </>
  );
}

function EN() {
  return (
    <>
      <h2>1. The service</h2>
      <p>
        MyHim Studio (the <strong>"Service"</strong>) is a cloud-based AI creative tool that lets users
        generate images and videos from text prompts. The Service is operated by Shenzhen Heshibi Technology
        Co., Ltd. (合势必科技, the <strong>"Operator"</strong>).
      </p>

      <h2>2. Eligibility</h2>
      <ul>
        <li>You must be at least 18 years old (or the legal age of majority in your jurisdiction, whichever is higher).</li>
        <li>Use of the Service must be legal in your region.</li>
        <li>You must provide a valid email address to register.</li>
      </ul>

      <h2>3. User content &amp; responsibility</h2>
      <p>You are fully and exclusively responsible for the prompts you enter and every output you generate. You specifically agree <strong>not</strong> to use the Service to generate, store, or share:</p>
      <ul>
        <li><strong className="text-fg">Child Sexual Abuse Material (CSAM)</strong> — zero tolerance. Confirmed reports are forwarded to NCMEC (US) and other competent authorities.</li>
        <li>Non-consensual intimate imagery (NCII) of any real person — including but not limited to celebrity face-swaps and deepfake pornography. This violates the US <em>TAKE IT DOWN Act (2025)</em> and similar laws in the EU, UK, AU, and many other jurisdictions.</li>
        <li>Content intended to defraud, harass, intimidate, or incite hatred or violence.</li>
        <li>Content that violates the laws of the jurisdiction where the depicted subject or audience resides.</li>
        <li>Content infringing third-party copyright, trademark, patent, right of publicity, or other IP.</li>
      </ul>
      <p>Violation of any clause above results in immediate account termination, forfeiture of remaining credits, and possible referral to authorities.</p>

      <h2>4. AI output disclaimer</h2>
      <p>Outputs are generated by AI models and may be inaccurate, biased, or fictional. You agree NOT to rely on outputs for:</p>
      <ul>
        <li>medical, legal, financial, or other professional advice;</li>
        <li>real-event reporting or journalism;</li>
        <li>any representation that the output depicts a real, identifiable person.</li>
      </ul>

      <h2>5. Intellectual property</h2>
      <p>Subject to your compliance with these Terms, you obtain a worldwide license to use, modify, and commercially exploit the images and videos you generate (subscribers only — free-tier outputs are for personal use). Please note:</p>
      <ul>
        <li>AI-generated content generally <strong className="text-fg">does not qualify for copyright protection</strong> in most jurisdictions (e.g. US Copyright Office, 2023 ruling).</li>
        <li>If your prompts or uploaded references include protected works, you are solely responsible for clearing those rights.</li>
        <li>You grant the Operator a limited, non-exclusive licence to store your outputs solely for the purpose of providing the Service to you.</li>
      </ul>

      <h2>6. Payments, refunds &amp; termination</h2>
      <p>
        Credits are purchased via cryptocurrency (NowPayments) or card (Paddle, where available). All prices are in USD.
        See the <a href="/legal/refund">Refund Policy</a> for refund eligibility. We may suspend or terminate accounts that
        violate these Terms, with credits forfeited.
      </p>

      <h2>7. Service availability</h2>
      <p>
        The Service is provided <strong>AS IS</strong> and <strong>AS AVAILABLE</strong>, without warranties of any kind.
        We strive for high uptime but do not guarantee uninterrupted or error-free operation. For outages caused by force majeure
        or third-party failures (RunPod, Cloudflare, etc.), we will reasonably refund unconsumed credits.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, the Operator's aggregate liability arising out of or related to the Service
        will not exceed the greater of (a) the amount you paid us in the 12 months before the claim arose, or (b) USD 100.
        We are not liable for indirect, incidental, consequential, special, or exemplary damages.
      </p>

      <h2>9. Indemnification</h2>
      <p>
        You agree to indemnify and hold the Operator harmless from any third-party claim arising from your use of the Service,
        including any prompt you submit and any output you generate, store, share, or commercialise.
      </p>

      <h2>10. Governing law &amp; disputes</h2>
      <p>
        These Terms are governed by the laws of the People's Republic of China (excluding conflict-of-laws rules) for users
        contracting with the Shenzhen entity. Disputes will first be addressed by good-faith negotiation; failing that,
        submitted to arbitration in Shenzhen under the rules of the South China International Economic and Trade Arbitration
        Commission (SCIA). For users in jurisdictions where mandatory consumer protection laws apply (e.g. EU consumers), those
        protections take precedence over this clause.
      </p>

      <h2>11. Changes</h2>
      <p>We may update these Terms from time to time. Material changes will be emailed to registered users at least 14 days before they take effect. Continued use after the effective date constitutes acceptance.</p>

      <h2>12. Contact</h2>
      <p>Questions: <a href="mailto:legal@myhim.love">legal@myhim.love</a></p>
    </>
  );
}

function ZH() {
  return (
    <>
      <h2>1. 服务说明</h2>
      <p>
        MyHim Studio（"本服务"）是一款基于云端的 AI 创作工具，允许用户根据文本提示生成图像与视频。
        本服务由 深圳合势必科技有限公司 提供。
      </p>

      <h2>2. 准入要求</h2>
      <ul>
        <li>用户必须年满 18 周岁，或所在司法辖区规定的成年年龄（以较大者为准）</li>
        <li>使用本服务在用户所在地区必须合法</li>
        <li>用户须提供真实有效的电子邮箱以便注册账户</li>
      </ul>

      <h2>3. 用户内容与责任</h2>
      <p>用户对其输入的提示词（prompts）与生成的所有输出内容承担全部法律责任。用户特别承诺<strong className="text-fg">不会</strong>使用本服务生成或传播以下内容：</p>
      <ul>
        <li>儿童性虐待材料（CSAM）—— 零容忍，将立即报告执法机关</li>
        <li>未经本人同意的真人身份图像（包括但不限于名人换脸、deepfake 色情）</li>
        <li>用于欺诈、骚扰、煽动仇恨、人身威胁的内容</li>
        <li>违反目标个体所在地法律的内容</li>
        <li>侵犯第三方版权、商标、专利、肖像权或其他知识产权的内容</li>
      </ul>
      <p>违反上述任一条款将导致账户被立即终止、积分作废，且我方可能向执法机关移交相关数据。</p>

      <h2>4. 内容生成的免责</h2>
      <p>本服务输出的内容由 AI 模型基于用户提示词生成，可能包含不准确、不真实或带有偏见的元素。用户不应将生成内容用于：</p>
      <ul>
        <li>医疗、法律、财务或其他需要专业资质的建议</li>
        <li>真实事件报道或新闻素材</li>
        <li>声称为真实人物拍摄的影像</li>
      </ul>

      <h2>5. 知识产权</h2>
      <p>在用户遵守本条款的前提下，用户对其生成的图像与视频享有商业使用权（仅订阅用户）。但需注意：</p>
      <ul>
        <li>AI 生成内容在多数司法辖区<strong className="text-fg">不享受著作权保护</strong>（如美国版权局 2023 年裁定）</li>
        <li>用户输入的提示词与上传的参考图，如包含受保护作品，需由用户自行处理版权问题</li>
      </ul>

      <h2>6. 付费、退款与终止</h2>
      <p>
        积分通过加密货币（NowPayments）或信用卡（Paddle，未来开放）购买。所有交易以美元计价。
        详细退款规则见 <a href="/legal/refund">退款政策</a>。
      </p>

      <h2>7. 服务可用性</h2>
      <p>
        本服务以"现状（AS IS）"提供。我们尽力维持高可用性，但不保证服务连续可用或无错误。
        因不可抗力（包括但不限于第三方 API 故障、GPU 资源短缺）导致的服务中断，我们将合理范围内退还未消费的积分。
      </p>

      <h2>8. 责任限制</h2>
      <p>
        在法律允许的最大范围内，运营方因本服务产生或相关的累计责任不超过 (a) 用户在索赔事项发生前 12 个月内向我方支付的金额，
        或 (b) 100 美元，以较大者为准。我们不对间接、附带、衍生、特殊或惩罚性损害承担责任。
      </p>

      <h2>9. 司法管辖与争议解决</h2>
      <p>
        本条款受中华人民共和国法律管辖。任何争议应首先通过友好协商解决；
        协商不成时，提交深圳国际仲裁院（SCIA）仲裁。
      </p>

      <h2>10. 条款变更</h2>
      <p>我们可能不时更新本条款。重大变更将通过邮件通知所有注册用户。继续使用本服务即视为接受变更后的条款。</p>

      <h2>11. 联系方式</h2>
      <p>如对本条款有任何疑问，请联系：<a href="mailto:legal@myhim.love">legal@myhim.love</a></p>
    </>
  );
}
